#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org'
#source 'https://github.com/emqx/CocoaMQTT'

platform :ios, '11.3'
use_frameworks!

target 'Patriot' do
    pod "CocoaMQTT"
    pod "Particle-SDK"
end
