homeassistant: false
permit_join: false   #set to true to add new zigbee devices
mqtt:
  base_topic: patriot/zigbee
  server: mqtt://192.168.0.33
serial:
  port: /dev/tty.usbserial-8330
#  adapter: znp   #set to ezsp for -E adapter
advanced:
  pan_id: 49286
  network_key:
    - 22
    - 167
    - 211
    - 98
    - 3
    - 175
    - 242
    - 78
    - 3
    - 222
    - 229
    - 43
    - 9
    - 130
    - 174
    - 249
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00124b002a62f3dc':
    friendly_name: FrontDoor
  '0x00124b002a62f09e':
    friendly_name: RampDoor
  '0x00124b002c3a283a':
    friendly_name: PlantLight
  '0x00124b002c3a3fcd':
    friendly_name: OfficeValence
  '0x00124b002fa16de3':
    friendly_name: CoffeeMotion
  '0x00124b002c3a2843':
    friendly_name: WorkBench
  '0xb0ce1814000dcdd0':
    friendly_name: LeftDeskLamp
  '0xb0ce1814000dc403':
    friendly_name: NookLamp
  '0xb0ce1814000dc56a':
    friendly_name: RightDeskLamp
  '0xb0ce1814000db8e9':
    friendly_name: BedroomLamp
